name: ClientWorker 
cleaninterval: 1000*30 # 每30秒检测并清理一次缓存
# ClientWorker热补丁
hotpatch:
  - https://raw.githubusercontent.com/ChenYFan/ClientWorker/gh-pages/cw.js
  - https://cdn.jsdelivr.net/gh/ChenYFan/ClientWorker/cw.js
catch_rules: #转换规则
    - rule: _ #ClientWorker语法糖，匹配当前域，返回一个域名带端口
      transform_rules: #转换规则，最上面的优先最高
        - search: \#.* #在发送请求时匹配#后内容并移除
          replace: ''
        - search: \?.* #在发送请求时匹配?后内容并移除，仅限静态请求
          replace: '' 
        - search: _ 
          replace: 
          - _ #保留原始请求
          - phosoft.cn #Vercel托管
          - netlify.phosoft.cn #Netlify托管
          - cloudflarepage.phosoft.cn #cloudflarepage托管
          - phosoftweb-home-phosoft-61af00d8bdb427ac667f569518a84fdd3466e22.gitlab.io #gitlab托管

        - search: \.html$
          header:
            Content-Type: text/html;charset=UTF-8 #修复标头

        - search: _
          action: fetch
          fetch:
            status: 200
            engine: parallel
            preflight: false
            timeout: 5000
